name: Create Release

on:
  push:
    branches:
    - main

jobs:
  unit:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker Multi-Platform Builds
      run: |
        docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
    - name: Run Tests
      run: go test -v -count=1 ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: unit
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Checkout
      uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
    - name: Reset Draft Release
      id: reset
      uses: paketo-buildpacks/github-config/actions/release/reset-draft@main
      with:
        repo: ${{ github.repository }}
        token: ${{ github.token }}
    - name: Tag
      id: tag
      uses: paketo-buildpacks/github-config/actions/tag/increment-tag@main
      with:
        current_version: ${{ steps.reset.outputs.current_version }}
    - name: Package Jam
      run : ./scripts/package.sh --version ${{ steps.tag.outputs.tag }}
    - name: Create Draft Release
      uses: paketo-buildpacks/github-config/actions/release/create@main
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        tag_name: v${{ steps.tag.outputs.tag }}
        target_commitish: ${{ github.sha }}
        name: v${{ steps.tag.outputs.tag }}
        draft: true
        assets: |
          [
            {
              "path": "build/jam-darwin",
              "name": "jam-darwin",
              "content_type": "application/octet-stream"
            },
            {
              "path": "build/jam-linux",
              "name": "jam-linux",
              "content_type": "application/octet-stream"
            },
            {
              "path": "build/jam-windows.exe",
              "name": "jam-windows.exe",
              "content_type": "application/octet-stream"
            }
          ]

